### PR TITLE
Upgrade to 23.9.9

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
:shrug: 
```
dpp: $SRC_DIR/src/c/string.d -> string.o.c
Error in line 902: Function SI::BASE-STRING-CONCATENATE: wrong declaration for number of required arguments, expected 1, but got 0.
```

**Comment by saraedum** [comment]
@isuruf @embray if you have any insights into what's going on here, help is appreciated. Otherwise, I'll ask upstream.

**Comment by saraedum** [comment]
GitLab doesn't let me log in currently. I'll try again later hopefully.

**Comment by isuruf** [comment]
For the cross compilation here to work, I think you need the same version of ecl in build. We can merge here, wait for osx-64 package to upload and restart. Or we can remove `ecl` from build and build the osx-64 when cross compiling for osx-arm64

**Comment by saraedum** [comment]
> For the cross compilation here to work, I think you need the same version of ecl in build.

Makes sense.

> We can merge here, wait for osx-64 package to upload and restart.

Sounds annoying but reasonable. Let me add a pin and a comment.

> Or we can remove `ecl` from build and build the osx-64 when cross compiling for osx-arm64

That sounds quite complicated. If there's some easy way to run ./build.sh against the build prefix with the correct environment variables, then maybe that's a good idea. But it's probably not worth it and easier to document how this works and just merge.

**Comment by saraedum** [comment]
@isuruf, great. That worked :)

**Pull request merged**
