### PR TITLE
WIP: Downgrade ecl

### PR DESCRIPTION
**Pull request by saraedum**
to provide a version of ecl that works with SageMath, see https://github.com/conda-forge/sage-feedstock/pull/24.

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by isuruf** [comment]
Are all patches from sage used here? If so, +1 to merge to a new branch `16.1.2`

**Comment by saraedum** [comment]
I see, we should have an extra branch if we want to keep old versions around?

**Comment by isuruf** [comment]
> I see, we should have an extra branch if we want to keep old versions around?

Yes.

**Comment by saraedum** [comment]
Ok. Let me prepare this here and then push to that branch when we're happy with it.

**Comment by saraedum** [comment]
Pushed this to a 16.1.2 branch.

**Pull request closed without merging**
